export interface CourseDetail {
    id: number
    university_id: number
    level: number
    chinese_name: string
    english_name: string
    chinese_title: string
    english_title: string
    chinese_introduction: string
    english_introduction: string
    duration: string
    image_url: string
    chinese_carousel_url: string
    english_carousel_url: string
    wap_carousel_url: string
    wap_video_url: string
    wap_image_url: string
    wap_image_link: string
    start_enter_school: number
    start_enter_school_year: Array<string>
    start_enter_school_month: Array<string>
    service_charge_gbp: number
    service_charge_rmb: number
    tuition_fee_gbp: number
    tuition_fee_rmb: number
    buy_multiple_at_a_time: number
    course_link: string
    course_university_link: string
    chinese_requirement: string
    english_requirement: string
    sales: number
    is_discount: number
    discount_amount: number
    show_on_mobile: number
    status: number
    is_top: number
    ranking: number
    operator_id: number
    is_thirdpart: number
    binding_thirdpart_id: null
    created_at: number
    updated_at: number
    first_category_id: string
    second_category_id: string
    uuid: string
    view_counter: number
    business_type: number
    can_create_order: number
    levelNameEnglish: string
    levelNameChinese: string
}
